// <auto-generated />
using System;
using DbOperationsWithEFCoreApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbOperationsWithEFCoreApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250706111112_DataUpate")]
    partial class DataUpate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("NoOfPages")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOn = new DateOnly(2024, 1, 1),
                            Description = "A beginner's book for ASP.NET Core and EF Core.",
                            IsActive = true,
                            LanguageId = 1,
                            NoOfPages = 350,
                            Title = "Learn ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            CreatedOn = new DateOnly(2023, 10, 15),
                            Description = "Advanced guide to C# programming.",
                            IsActive = true,
                            LanguageId = 1,
                            NoOfPages = 500,
                            Title = "Mastering C#"
                        },
                        new
                        {
                            Id = 3,
                            CreatedOn = new DateOnly(2022, 5, 20),
                            Description = "Web design with HTML and CSS.",
                            IsActive = true,
                            LanguageId = 2,
                            NoOfPages = 280,
                            Title = "HTML & CSS Design"
                        },
                        new
                        {
                            Id = 4,
                            CreatedOn = new DateOnly(2021, 8, 10),
                            Description = "Learn SQL from scratch.",
                            IsActive = true,
                            LanguageId = 3,
                            NoOfPages = 320,
                            Title = "Introduction to SQL"
                        },
                        new
                        {
                            Id = 5,
                            CreatedOn = new DateOnly(2024, 3, 5),
                            Description = "Core concepts of JavaScript.",
                            IsActive = true,
                            LanguageId = 1,
                            NoOfPages = 400,
                            Title = "JavaScript Essentials"
                        });
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.BookPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("CurrencyId");

                    b.ToTable("BookPrice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 29.99m,
                            BookId = 1,
                            CurrencyId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 39.99m,
                            BookId = 2,
                            CurrencyId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 19.99m,
                            BookId = 3,
                            CurrencyId = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 24.50m,
                            BookId = 4,
                            CurrencyId = 3
                        },
                        new
                        {
                            Id = 5,
                            Amount = 34.99m,
                            BookId = 5,
                            CurrencyId = 1
                        });
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrencyType = "INR",
                            Description = "Indian INR"
                        },
                        new
                        {
                            Id = 2,
                            CurrencyType = "Dollar",
                            Description = "Dollar"
                        },
                        new
                        {
                            Id = 3,
                            CurrencyType = "Euro",
                            Description = "Euro"
                        },
                        new
                        {
                            Id = 4,
                            CurrencyType = "Dinar",
                            Description = "Dinar"
                        });
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Books written in English",
                            Title = "English"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Books written in Hindi",
                            Title = "Hindi"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Books written in Nepali",
                            Title = "Nepali"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Books written in French",
                            Title = "French"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Books written in Spanish",
                            Title = "Spanish"
                        });
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Book", b =>
                {
                    b.HasOne("DbOperationsWithEFCoreApp.Data.Language", "Language")
                        .WithMany("Books")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.BookPrice", b =>
                {
                    b.HasOne("DbOperationsWithEFCoreApp.Data.Book", "Book")
                        .WithMany("Prices")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DbOperationsWithEFCoreApp.Data.Currency", "Currency")
                        .WithMany("Prices")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Book", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Currency", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("DbOperationsWithEFCoreApp.Data.Language", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
